### ISSUE TITLE
دسترسی ادمین به یک اینباند

### ISSUE THREAD

**Issue by usamirali** [dev-ir/xui-assistant#1]
سلام و خسته نباشید لطفا در اپدیت بعدی کاری کنید بتونیم دسترسی یک مدیر به یک اینباند رو بدیم

**Comment by dev-ir** [comment]
درود
تغیین سطح دسترسی هنوز در ساختار xui تعریف نشده اما به زودی در نسخه علیرضا پشتیبانی خواهد کرد _ با همراهی علیرضا عزیز

**Comment by masoudsolo** [comment]
تعین سطع دسترسی برای اینکه به یک نفر اکسس ادمینی بدهیم نتونه یوزر رو ریست کنه یا تغیر در تاریخ بده  و سر ماه ببینیم چند یوزر ساخته برای حساب کتاب سر ماه خیلی مهم است با تشکر
