### ISSUE TITLE
پشتیبانی از پنل مرزبان

### ISSUE THREAD

**Issue by ManiXD** [dev-ir/xui-assistant#2]
این اسکریپت از پنل مرزبان هم پشتیبانی میکنه یا خیر؟

**Comment by dev-ir** [comment]
سلام
همانطور که از نامش پیداست برای xui طراحی شده است 
و به زودی برای مرزبان هم یک دستیار در نظر گرفتیم

**Comment by ManiXD** [comment]
متشکر فقط تایم دقیقی از انتشار دستیار مرزبان دارید؟

**Comment by dev-ir** [comment]
> متشکر فقط تایم دقیقی از انتشار دستیار مرزبان دارید؟

اواسط مهرماه با ویژگی های جدید ارائه میشود
