### ISSUE TITLE
ارور

### ISSUE THREAD

**Issue by zingunlock** [dev-ir/xui-assistant#3]
ممنون بابت حركت خفنتون

فقط من تو گزينه ٣ باين مورد مواجه ميشم

Traceback (most recent call last):
File "core/user_manager.py", line 141, in <module> main (
File "core/user_manager py", line 117, in main dvhost_list_users ()
File "core/user_manager -py", line 98, in dvhost_list_u
sers cursor. execute ("SELECT id, username, password, login
_secret FROM users ORDER BY id")
salite3. OperationalError: no such column: login_secret root@Pp:~#

**Comment by dev-ir** [comment]
درود 
ورژن و سیستم عامل بفرمایید

**Comment by raminol12** [comment]
ابونتو 20 

این مشکل همچنان موجود است چندین بار سرور و دیتاسنتر عوض کردم ولی بعد از نصب ربات دستیار شما دیگه روی سرور هیچ کاری رو نمیشه انجام داد .

root@ubuntu-4gb-nbg1-22:~# apt update -y
Hit:1 https://mirror.hetzner.com/ubuntu/packages focal InRelease
Hit:2 https://mirror.hetzner.com/ubuntu/packages focal-updates InRelease
Hit:3 https://mirror.hetzner.com/ubuntu/packages focal-backports InRelease
Hit:4 https://mirror.hetzner.com/ubuntu/security focal-security InRelease
Hit:5 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Traceback (most recent call last):
  File "/usr/lib/cnf-update-db", line 8, in <module>
    from CommandNotFound.db.creator import DbCreator
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 12, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
Reading package lists... Done
E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
E: Sub-process returned an error code


هیچ چیزی نصب نمیشه و این ارور رو دارم

**Comment by dev-ir** [comment]
حداقل نسخه اوبونتو 22 هست
