### ISSUE TITLE
لو رفتن یوزر و پس همه ادمین ها

### ISSUE THREAD

**Issue by aminimahdi112** [dev-ir/xui-assistant#4]
سلام این اسکریپت یک باگ اساسی داره که امیدوارم هر چه سریع تر حل بشه . مشکل اینجاس به فرض ادمین شماره 3 مبتونه یک بکاپ از دیتابیس تهیه کنه و روی بک سرور دیگه این دیتابیس رو بالا بیاره بعد میتونه این اسکریپت رو نصب کنه از قسمت manage users به تمامی یوزر ها و پسورد های ادمین ها دسترسی پیدا کنه و از سرور اصلی به پنل های سایر ادمین ها وارد بشه و مشکل ایجاد کنه . امیدوارم این مشکل رو حل کنید 
راه حل پیشنهادی من اینه برای قسمت manage user بشه یک پسورد تعیین کرد که هیچکس بجز ادمین اصلی نتونه وارد بشه

**Comment by aminimahdi112** [comment]
درسته ولی میشه از اسکریپت هم کارایی کرد که امنیت بالاتر بره . نظر من اینه تو قسمت manage users فقط یوزر نیم ها نمایش داده بشه و رمز ها مخفی بمونن .

**Comment by dev-ir** [comment]
> درسته ولی میشه از اسکریپت هم کارایی کرد که امنیت بالاتر بره . نظر من اینه تو قسمت manage users فقط یوزر نیم ها نمایش داده بشه و رمز ها مخفی بمونن .

اسکریپت توسط ادمین اصلی سرور قابل دسترسی هست و مجاز هست دسترسی کاربرانش چک کند که چندان فرقی برای ادمین که روت سرور داره نداره چون داخل دیتابیس هم رمزها داراست
