### ISSUE TITLE
کار نکردن بات

### ISSUE THREAD

**Issue by mahdinosrati** [dev-ir/xui-assistant#8]
سیستم عاملم ابونتو 24 و اینکه پنل ها هم pach دارن هم https با اینا مشکلی نداره؟! چون کار نکرد برای من

**Comment by dev-ir** [comment]
درود
در ویدئو گفته شده فقط با 22 فعلا سازگار هست تا در اپدیت های بعدی هسته به 24 ارتقاع خواهیم داد
