### ISSUE TITLE
ارور 

### ISSUE THREAD

**Issue by raminol12** [dev-ir/xui-assistant#9]
این مشکل همچنان موجود است چندین بار سرور و دیتاسنتر عوض کردم ولی بعد از نصب ربات دستیار شما دیگه روی سرور هیچ کاری رو نمیشه انجام داد . قبل از استفاده از اسکریپت شما هیچ مشکلی نیست
سیستم عامل : ابونتو 20

root@ubuntu-4gb-nbg1-22:~# apt update -y
Hit:1 https://mirror.hetzner.com/ubuntu/packages focal InRelease
Hit:2 https://mirror.hetzner.com/ubuntu/packages focal-updates InRelease
Hit:3 https://mirror.hetzner.com/ubuntu/packages focal-backports InRelease
Hit:4 https://mirror.hetzner.com/ubuntu/security focal-security InRelease
Hit:5 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Traceback (most recent call last):
File "/usr/lib/cnf-update-db", line 8, in
from CommandNotFound.db.creator import DbCreator
File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 12, in
import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
Reading package lists... Done
E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
E: Sub-process returned an error code

هیچ چیزی نصب نمیشه و این ارور رو دارم

**Comment by dev-ir** [comment]
حداقل نسخه 22 هست
